#import "../sophiatheme.typ": *
#show: sophia-theme
#show figure.caption: it => [
#set text(size: 20pt)
#it.body
]


#slide()[
#text(size: 30pt, weight: "bold")[Pump Efficiency]
#v(40pt)
#only("1-")[Which type of pump is most efficient for agricultural irrigation?]
#v(40pt)
// From the start until section one, the option is black. From section 2 until the end it is then turned green, because it is correct. 
#only("-1")[a) Centrifugal]#only("2-")[#text(fill:green)[a) Centrifugal]]
#v(10pt)
// From the start until section two, the option is black. From section 3 until the end it is then turned red, because it is false.
#only("-2")[b) Piston]#only("3-")[#text(fill:red)[b) Piston]]
#v(10pt)
// From the start until section three, the option is black. From section 4 until the end it is then turned red, because it is false.
#only("-3")[c) Diaphragm]#only("4-")[#text(fill:red)[c) Diaphragm]]
#v(10pt)
// From the start until section four, the option is black. From section 5 until the end it is then turned red, because it is false.
#only("-4")[d) Peristaltic]#only("5-")[#text(fill:red)[d) Peristaltic]]
#v(40pt)

#only("1")[#voiceover("Great job! The correct answer is...")]
// Very briefly Talk about a and why it is correct
#only("2")[#voiceover("a) Centrifugal pumps. They are indeed the most efficient type for agricultural irrigation. Let's see why.")]
// Very briefly Talk about b and why it is incorrect
#only("3")[#voiceover("b) Piston pumps are not as efficient. They are better suited for high-pressure, low-flow applications.")]
// Very briefly Talk about c and why it is incorrect
#only("4")[#voiceover("c) Diaphragm pumps, while reliable, are also not as efficient as centrifugal pumps for this application.")]
// Very briefly Talk about d and why it is incorrect
#only("5")[#voiceover("And d) Peristaltic pumps are typically used for smaller scale, precise dosing applications, not large-scale irrigation.")]

]

#slide()[
#text(size: 30pt, weight: "bold")[Why Centrifugal Pumps? 🌀]
#v(40pt)
#only("1-")[
- High flow rates 🌊
]
#only("2-")[
- Steady, non-pulsating flow 📈
]
#only("3-")[
- Simple design, easy maintenance 🔧
]
#only("4-")[
- Can handle solids and debris 🍂
]
#only("5-")[
- Energy efficient ⚡
]

#only("1")[#voiceover("Centrifugal pumps are ideal for irrigation because they can provide high flow rates.")]
#only("2")[#voiceover("They deliver a steady, non-pulsating flow, which is important for even watering.")]
#only("3")[#voiceover("Their simple design makes them easy to maintain and repair.")]
#only("4")[#voiceover("Centrifugal pumps can handle some solids and debris, which is common in irrigation water.")]
#only("5")[#voiceover("Most importantly, they are energy efficient, which is crucial for large-scale, continuous operation in agriculture.")]
]

#slide()[
#text(size: 30pt, weight: "bold")[How They Work]
#v(40pt)
#box()[
#morphchildren(id: "plot")[
#figure(
pyimage(``` 
import matplotlib.pyplot as plt 
import numpy as np 
from matplotlib.patches import Arc, Arrow 

fig, ax = plt.subplots(figsize=(8, 8)) 

circle = plt.Circle((0.5, 0.5), 0.4, fill=False) 

inlet = Arrow(0.2, 0.5, 0.2, 0, width=0.05, color='blue') 
outlet = Arrow(0.8, 0.5, 0.2, 0, width=0.05, color='red') 

impeller = plt.Circle((0.5, 0.5), 0.2, fill=False, color='green') 

arc1 = Arc((0.5, 0.5), 0.4, 0.4, angle=0, theta1=0, theta2=90, color='green') 
arc2 = Arc((0.5, 0.5), 0.4, 0.4, angle=0, theta1=90, theta2=180, color='green') 
arc3 = Arc((0.5, 0.5), 0.4, 0.4, angle=0, theta1=180, theta2=270, color='green') 
arc4 = Arc((0.5, 0.5), 0.4, 0.4, angle=0, theta1=270, theta2=360, color='green') 

ax.add_patch(circle) 
ax.add_patch(inlet) 
ax.add_patch(outlet) 
ax.add_patch(impeller) 
ax.add_patch(arc1) 
ax.add_patch(arc2) 
ax.add_patch(arc3) 
ax.add_patch(arc4) 

ax.set_xlim(0, 1) 
ax.set_ylim(0, 1) 
ax.set_aspect('equal') 
ax.set_xticks([]) 
ax.set_yticks([]) 

ax.annotate('Inlet', xy=(0.1, 0.55)) 
ax.annotate('Outlet', xy=(0.8, 0.55)) 
ax.annotate('Impeller', xy=(0.45, 0.5)) 

plt.show() 
```, 
width: 360pt), 
) 
] 
] 
#v(40pt) 
#only("1-")[ 
1. Water enters through the #text(fill:blue)[inlet] 🔵 
] 
#only("2-")[ 
2. Rotating #text(fill:green)[impeller] spins the water 🌀 
] 
#only("3-")[ 
3. Centrifugal force pushes water outward 🌠 
] 
#only("4-")[ 
4. Water exits through the #text(fill:red)[outlet] 🔴 
] 

#only("1")[#voiceover("Here's a simple diagram of how a centrifugal pump works. Water enters the pump through the inlet, shown in blue.")] 
#only("2")[#voiceover("Inside, a rotating impeller, shown in green, spins the water.")] 
#only("3")[#voiceover("Centrifugal force generated by the spinning impeller pushes the water outward.")] 
#only("4")[#voiceover("The water is then discharged through the outlet, shown in red, at a higher velocity and pressure than at the inlet.")] 
]

#slide()[
#text(size: 30pt, weight: "bold")[Summary]
#v(40pt)
#only("1-")[
- Centrifugal pumps are most efficient for irrigation 🌾
]
#only("2-")[
- They provide high flow, steady output 🚰
]
#only("3-")[
- Simple, low-maintenance design 🔧
]
#only("4-")[
- Centrifugal force is the key principle 🌀
]

#only("1")[#voiceover("To recap, centrifugal pumps are the most efficient choice for agricultural irrigation.")]
#only("2")[#voiceover("They provide the high, steady flow rates needed for large-scale watering.")]
#only("3")[#voiceover("Their simple design makes them reliable and easy to maintain.")]
#only("4")[#voiceover("And they harness the power of centrifugal force to move water efficiently. Great work on identifying the correct answer!")]
]