#import "../sophiatheme.typ": *
#show: sophia-theme
#show figure.caption: it => [
#set text(size: 20pt)
#it.body
]


#slide()[
#text(size: 30pt, weight: "bold")[Fundamental Analysis]
#v(40pt)
#only("1-")[- Assesses a company's financial health 🩺]
#v(20pt)
#only("2-")[- Uses indicators like:]
#v(10pt)
#only("3-")[  - Earnings 💰]
#v(10pt)
#only("4-")[  - Market Share 📊]
#v(10pt)
#only("5-")[  - Financial Statements 📜]
#only("1")[
#voiceover("Fundamental Analysis is a method used to assess a company's financial health and intrinsic value.")
]
#only("2")[
#voiceover("It uses various indicators to determine if a stock is worth investing in.")
]
#only("3")[
#voiceover("One key indicator is the company's earnings. Analysts look at the company's profits and revenue growth over time.")
]
#only("4")[
#voiceover("Another important factor is the company's market share. This shows how well the company is performing compared to its competitors.")
]
#only("5")[
#voiceover("Financial statements, such as balance sheets and cash flow statements, provide detailed insights into the company's financial situation.")
]
]

#slide()[
#text(size: 30pt, weight: "bold")[Earnings]
#v(40pt)
#only("1-")[- Profits generated by the company 📈]
#v(20pt)
#only("2-")[- Indicator of financial performance 💪]
#v(20pt)
#only("3-")[- Analyzed over time for growth 📅]
#only("1")[
#voiceover("Let's take a closer look at earnings. Earnings refer to the profits generated by a company.")
]
#only("2")[
#voiceover("It's a key indicator of a company's financial performance. Higher earnings generally indicate a healthier company.")
]
#only("3")[
#voiceover("Analysts look at earnings growth over time to see if the company is consistently improving its profitability.")
]
]

#slide()[
#text(size: 30pt, weight: "bold")[Market Share]
#v(40pt)
#only("1-")[- Company's portion of the total market 🍕]
#v(20pt)
#only("2-")[- Indicates competitive position 🏆]
#v(20pt)
#only("3-")[- Higher market share often means better prospects 📈]
#only("1")[
#voiceover("Market share is another crucial indicator. It represents the company's portion of the total market for its products or services.")
]
#only("2")[
#voiceover("Market share indicates a company's competitive position. A company with a high market share is usually a market leader.")
]
#only("3")[
#voiceover("Companies with higher market shares often have better prospects for growth and profitability.")
]
]

#slide()[
#text(size: 30pt, weight: "bold")[Financial Statements]
#v(40pt)
#only("1-")[- Balance Sheet: Assets, Liabilities, Equity ⚖️]
#v(20pt)
#only("2-")[- Income Statement: Revenues, Expenses, Profits 💸]
#v(20pt)
#only("3-")[- Cash Flow Statement: Cash Inflows and Outflows 🌊]
#only("1")[
#voiceover("Financial statements provide a wealth of information for fundamental analysts. The balance sheet shows a company's assets, liabilities, and equity at a point in time.")
]
#only("2")[
#voiceover("The income statement reports a company's revenues, expenses, and profits over a period of time.")
]
#only("3")[
#voiceover("The cash flow statement shows how changes in balance sheet accounts and income affect cash and cash equivalents.")
]
]

#slide()[
#text(size: 30pt, weight: "bold")[Summary]
#v(40pt)
#only("1-")[- Fundamental Analysis assesses financial health 🩺]
#v(20pt)
#only("2-")[- Key indicators: Earnings 💰, Market Share 📊, Financial Statements 📜]
#v(20pt)
#only("3-")[- Helps determine a stock's intrinsic value 💎]
#only("1")[
#voiceover("In summary, Fundamental Analysis is a method to assess a company's financial health.")
]
#only("2")[
#voiceover("It uses key indicators like earnings, market share, and financial statements to get a comprehensive view of a company's performance and prospects.")
]
#only("3")[
#voiceover("By analyzing these factors, investors can determine a stock's intrinsic value and make informed investment decisions.")
]
]