#import "../sophiatheme.typ": *
#show: sophia-theme
#show figure.caption: it => [
#set text(size: 20pt)
#it.body
]


#slide()[
#text(size: 30pt, weight: "bold")[Stock Market Volatility]
#v(40pt)
#only("1-")[In stock market analysis, high standard deviation indicates:]
#v(40pt)
// From the start until section one, the option is black. From section 2 until the end it is then turned red, because it is false. 
#only("-1")[a) Less risk]#only("2-")[#text(fill:red)[a) Less risk]]
#v(10pt)
// From the start until section two, the option is black. From section 3 until the end it is then turned red, because it is false.
#only("-2")[b) More stability]#only("3-")[#text(fill:red)[b) More stability]]
#v(10pt)
// From the start until section three, the option is black. From section 4 until the end it is then turned green, because it is correct.
#only("-3")[c) Higher volatility]#only("4-")[#text(fill:green)[c) Higher volatility]]
#v(10pt)
// From the start until section four, the option is black. From section 5 until the end it is then turned red, because it is false.
#only("-4")[d) Fixed returns]#only("5-")[#text(fill:red)[d) Fixed returns]]
#only("1")[#voiceover("Sorry, that's not correct. Let's take a look at the right solution.")]
#only("2")[#voiceover("Less risk is not indicated by high standard deviation. In fact, it's the opposite.")]
#only("3")[#voiceover("More stability is also not associated with high standard deviation. Stability implies low variability.")]
#only("4")[#voiceover("Higher volatility is indeed what high standard deviation suggests in the context of stock markets. Volatility measures the dispersion of returns.")]
#only("5")[#voiceover("Fixed returns are not related to standard deviation. Standard deviation measures variability, not the level of returns.")]
]

#slide()[
#text(size: 30pt, weight: "bold")[Explanation]
#v(40pt)
#only("1-")[- Standard deviation measures the dispersion of data points 📊]
#v(20pt)
#only("2-")[- In stock markets, data points are typically returns 📈]
#v(20pt)
#only("3-")[- High standard deviation ⇒ returns are spread out 🌌]
#v(20pt) 
#only("4-")[- Spread out returns ⇒ stock price is volatile 🎢]
#only("1")[#voiceover("Let's break this down. Standard deviation is a statistical measure of the dispersion of data points from their mean.")]
#only("2")[#voiceover("In the context of stock markets, these data points are usually the returns generated by a stock over time.")]
#only("3")[#voiceover("A high standard deviation indicates that the returns are spread out over a wider range of values.")]
#only("4")[#voiceover("And when returns are spread out, it means the stock price is more volatile - it experiences larger swings.")]
]

#slide()[
#text(size: 30pt, weight: "bold")[Visualization]
#v(40pt)
#only("1-")[
#box()[
#morphchildren(id: "plot")[
#figure(
pyimage(```
import matplotlib.pyplot as plt
import numpy.py as np

# Generate sample data
low_volatility = np.random.normal(0, 1, 100)  # Low standard deviation
high_volatility = np.random.normal(0, 5, 100)  # High standard deviation

# Create the plot
plt.figure(figsize=(8, 6))
plt.plot(low_volatility, color='blue', label='Low Volatility')
plt.plot(high_volatility, color='red', label='High Volatility')
plt.title('Stock Returns: Low vs High Volatility')
plt.xlabel('Time')
plt.ylabel('Returns')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()
```,
width: 360pt))
]
]
#only("1")[#voiceover("Here's a visual representation. The blue line shows returns with low standard deviation, while the red line shows returns with high standard deviation.")]
#v(40pt)
#only("2-")[🔵 Low volatility ⇒ returns clustered around mean]
#v(20pt)
#only("3-")[🔴 High volatility ⇒ returns spread out]
#only("2")[#voiceover("With low volatility, the returns are clustered closely around the mean.")]
#only("3")[#voiceover("But with high volatility, the returns are much more spread out, indicating higher risk and less stability.")]
]
]

#slide()[
#text(size: 30pt, weight: "bold")[Key Takeaways]
#v(40pt)
#only("1-")[- High standard deviation ⇒ high volatility 📈]
#v(20pt)
#only("2-")[- High volatility ⇒ higher risk, less stability 🎢]
#v(20pt)
#only("3-")[- Investors often prefer low volatility 🧘]
#only("1")[#voiceover("To summarize, high standard deviation in stock returns indicates high volatility.")]
#only("2")[#voiceover("High volatility, in turn, implies higher risk and less stability in the stock price.")]
#only("3")[#voiceover("For this reason, many investors prefer stocks with low volatility, as they tend to offer a smoother, more predictable ride.")]
]